---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~2
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com/Klemantina/flux-get-started
    ref: master
    path: charts/ghost
  valuesFrom:
  - chartFileRef:
      path: for-ghost.yaml
      optional: false
